apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: dotnet
spec:
  build:
    resources: {}
  builder:
    kind: ClusterBuilder
    name: default
  cacheSize: 2G
  failedBuildHistoryLimit: 10
  imageTaggingStrategy: BuildNumber
  serviceAccount: default
  source:
    git:
      revision: master
      url: https://github.com/0pens0/dotnetcore-demo
    subPath: src
  successBuildHistoryLimit: 10
  tag: harbor.tanzuworld.com/apps/dotnet
