apiVersion: v1
kind: Service
metadata:
  labels:
    name: drupal
  name: drupal
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: drupal
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: harbor.tanzuworld.com/openso/drupal
        ports:
        - containerPort: 8080
