apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8s-app
  name: k8s-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: k8s-app
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
spec:
  selector:
    matchLabels:
      app: k8s-app
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: harbor.tanzuworld.com/apps/dotnetcore:latest
        ports:
        - containerPort: 8080
