apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5ekNDQWJPZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EWXlOREU0TVRnd04xb1hEVE13TURZeU1qRTRNak13TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkExCkFGa0lXcU14WlRIdzFYUW9aVmwwTVpIZ3JCMlI1RFFNZmdjODQvUUQrUFR4Y2pvMTBnRFRMbTRlbnpXYWFZQW8KcmFuS3FocHhmbnJLb3lQaFBuMXBaUk1DZjdMNTFDVHBJQjVjSXRIZzdGaFo0WVpvLytVbU1mQWlyeFhwaUlzWQpTekdrQWZhZG5SUmlLZEZaSDEwSVFVK3JRUUJhRzQxNnB3ZTJaVjB6dEpEdHpVaXUySUJIQmI4RG1HMHNFa3AxCmR2eDFNanBWRjc0Q2VmTTBIdzFvZlAxdi9VZDF2SXJuMWhsRnFvT2VTaXlMay8xVDV5R3FWWmdVVllLZlpZMk8KNko5cklpeGh6YTE3Q2VLTkpkOXk2Q1hodUJUN3BiM3VaYTdHWDVlM1ZIN3NMMW1vcmI0TE5oR3VrN3VOanYxTwpGVWlKdyt3V29zbStJRHk2NkdzQ0F3RUFBYU1tTUNRd0RnWURWUjBQQVFIL0JBUURBZ0trTUJJR0ExVWRFd0VCCi93UUlNQVlCQWY4Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSy9BNS9iMS9WdVlzVDZEalpVek94Q1QKVHdJN1VSZlFtZXpiNjdIKzlXaEJQSzRLaDJwM3c4Z3VTVXErUWJ5ZkFSQjExaEtCbXRQTlNLeHF2UndpLzVEMApDUEpTb2c5WWIybTVlWnVZOXAvYjNRV2ljNEtjRVd2ejFjcy92TUhNanpaOTdEa3dKNVR3QWhZNExwL1BHNC9HCjlDM2xrS1hxUHR4TnVqdXZhUlFXRXBiWGdrOFo4NERwbnhMOWZlT0oxUVlna2x3NVpLQ1RPR0FtU255Mk9WU1QKZ2ZDNmhWdCtoaDJmdzNscEVzOWd4ZUpIR3c5cHR3aEZhZUlVY2t0cC8vRXpmZEF2OUh1UkpzTGdrR0VtaGgySQpxV3dncE9BdFZZZGJnZ0s2ZG5FbWEwRFNOblErdW5ObEpRM1p5TmIyUUpzcEJYdmVLcUF2MUdrU21xWHBTM0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklubDJMV05UVm1sMGFua3haR1JCVVdsRFlYUkRlUzFMWlRKYVFUVmlXVFpsUTNaNGVXSm9UMUJ2UjJjaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKaGNtZHZZMlF0YldGdVlXZGxjaTEwYjJ0bGJpMXFPVEo0Y3lJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKaGNtZHZZMlF0YldGdVlXZGxjaUlzSW10MVltVnlibVYwWlhNdWFXOHZjMlZ5ZG1salpXRmpZMjkxYm5RdmMyVnlkbWxqWlMxaFkyTnZkVzUwTG5WcFpDSTZJamN4TkdNNVpESTNMVGxpTlRRdE5HWTFOUzFoTlRSbExXUTFNemt5WmpZMU9URmpOeUlzSW5OMVlpSTZJbk41YzNSbGJUcHpaWEoyYVdObFlXTmpiM1Z1ZERwcmRXSmxMWE41YzNSbGJUcGhjbWR2WTJRdGJXRnVZV2RsY2lKOS5ObjZWVUs2Zm9SUXF1cmlMYWJHZG1sU1I2TzhiNDZvdklneUFVSXFBV2JwWmFqNW9LTXIwTzRPdmpyZERRcjZlOXhjbloxN0tBbXlsdWN0NDYzVEp5NVZjekN3RGpKdzB2NklJOVo4S1FNYmUwOVVTVVVKZ2VSS2d2aXVlcHdoVnI5RjVnLTdvZHNGYWU5UVIzY090b3VBb2MyZU1NX0hVSzk0RmZKTEU5RTRKNkY3MXd0V2VGYnh3UzFOTjI2OFo5NW5GUVg5a0otVEpBMkRJT0hiVVd1T3BxczlDZzFsQTVoWE9ya043ZW9qZmpZcVhESUJaUWo0SVFxQjZvU3U1YVBxWGQ2UFZXWDJyVG1PWFdta1lCVldyV24tV1Z1dGhZUDJwT1MycnZQcEZhQk5jSWZLYTQ4cHdlS3dqQk9scEdzZXJKeDRLOTNsM3IyRzN0T3R3eEE=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: argocd-manager
    kubernetes.io/service-account.uid: 714c9d27-9b54-4f55-a54e-d5392f6591c7
  creationTimestamp: "2020-09-21T09:38:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-21T09:38:38Z"
  name: argocd-manager-token-j92xs
  namespace: kube-system
  resourceVersion: "60042166"
  selfLink: /api/v1/namespaces/kube-system/secrets/argocd-manager-token-j92xs
  uid: 32d63b86-f441-488d-af92-e65fb2e30bf4
type: kubernetes.io/service-account-token
