resource_types:
- name: kubernetes-prod
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "{{kubernetes-version-prod}}"
​
resources:
- name: kubernetes-cluster-prod
  type: kubernetes-prod
  icon: kubernetes
  source:
    insecure_skip_tls_verify: {{kubernetes-skip-tls-verification-prod}}
    kubeconfig: {{kubernetes-config-prod}}
    context: {{kubernetes-context-prod}}
    namespace: {{kubernetes-namespace}}
- name: container-image
  type: docker-image
  icon: docker
  source:
    repository: ((container-image))
​
jobs:
- name: deploy-image-prod
  plan:
  - get: container-image
    trigger: true
    params:
      skip_download: true
  - put: kubernetes-cluster-prod
    params:
      kubectl: |
        set image deployment ((kubernetes-deployment)) ((kubernetes-container))=$(cat container-image/repository)@$(cat container-image/digest)
      wait_until_ready: {{kubernetes-wait-until-ready-prod}}
  - task: sleep
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: sleep
        args:
        - 10
